version: '3.8'

services:
  eureka-server:
    build: ./untitled
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  comment-service:
    build: ./comments-service
    ports:
      - "8089:8089"
    depends_on:
      - untitled
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://untitled:8761/eureka/
    networks:
      - microservices-network

  api-gateway:
    build: ./Gateway
    ports:
      - "8080:8080"
    depends_on:
      - untitled
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://untitled:8761/eureka/
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
